# Generated by Django 5.0.6 on 2024-05-20 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('JAVA WORKS', 'JAVA WORKS'), ('NESCAFE', 'NESCAFE'), ('TIM HORTONS', 'TIM HORTONS'), ('ETHICAL BEAN', 'ETHICAL BEAN'), ('MAXWELL HOUSE', 'MAXWELL HOUSE'), ('FOLGERS', 'FOLGERS'), ('STARBUCK', 'STARBUCK'), ('NABOB', 'NABOB'), ('LAVAZZA', 'LAVAZZA'), ('49TH PARALLEL', '49TH PARALLEL'), ('KICKING HORSE', 'KICKING HORSE'), ('LIFEBOOST', 'LIFEBOOST'), ('VAN HOUTTE', 'VAN HOUTTE')], max_length=14)),
                ('price', models.IntegerField()),
                ('photo_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
