# Generated by Django 5.0.6 on 2024-05-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCoffee', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
