# Generated by Django 5.0.6 on 2024-06-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCoffee', '0008_order_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
