# Generated by Django 5.0.6 on 2024-06-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCoffee', '0010_alter_order_amount_alter_order_cart_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCoffee.cart'),
        ),
    ]
