# Generated by Django 5.0.6 on 2024-06-29 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCoffee', '0011_alter_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.PositiveIntegerField(default=0)),
                ('sub_total', models.FloatField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to='eCoffee.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eCoffee.product')),
            ],
        ),
    ]
